In [1]:
import pandas as pd
import numpy as np

fruit = pd.DataFrame({
    'name': ['apple', 'banana', 'cherry', 'durian', np.nan],
    'color': ['red', 'yellow', 'red', 'green', np.nan]
})

pd.get_dummies(fruit, dtype='int')

,name_apple,name_banana,name_cherry,name_durian,color_green,color_red,color_yellow
0,1,0,0,0,0,1,0
1,0,1,0,0,0,0,1
2,0,0,1,0,0,1,0
3,0,0,0,1,1,0,0
4,0,0,0,0,0,0,0

In [2]:
fruit

     name   color
0   apple     red
1  banana  yellow
2  cherry     red
3  durian   green
4     NaN     NaN

In [3]:
pd.get_dummies(fruit["name"], dtype='int64')

   apple  banana  cherry  durian
0      1       0       0       0
1      0       1       0       0
2      0       0       1       0
3      0       0       0       1
4      0       0       0       0

In [4]:
pd.get_dummies(fruit, columns=['name'], dtype='int64')

    color  name_apple  name_banana  name_cherry  name_durian
0     red           1            0            0            0
1  yellow           0            1            0            0
2     red           0            0            1            0
3   green           0            0            0            1
4     NaN           0            0            0            0